site_name: Web研究 MkDocs
site_url: https://swdcgghxa.github.io/Web_Notebook
site_dir: docs
docs_dir: md
dev_addr: localhost:1234
repo_name: GitHub
repo_url: https://github.com/swdcgghxa/Web_Notebook

theme:
  icon:
    repo: fontawesome/brands/git-square
  name: material

markdown_extensions:
  - attr_list
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: False
  - pymdownx.tabbed

# plugins:
#   - macros

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

nav:
    - Home: index.md
    - Python Web Framework:
        - Pyramid: python-web-framework/Pyramid.md
        - Djangorestframework: python-web-framework/Djangorestframework.md
        - Twisted: python-web-framework/Twisted.md
        - 訂製 Web 框架: python-web-framework/訂製 Web 框架.md
        - 框架參考.md: python-web-framework/框架參考.md
    - Python Web Gateway:
        - ASGI: python-web-gateway\Asgi.md
        - WSGI: python-web-gateway\Wsgi.md
    - Python Web Deploy:
        - Deploy方案: python-web-deploy/方案.md
        - 安全: python-web-deploy/安全.md
        - Tools: python-web-deploy/Tools.md
    - Web 負載均衡:
        - 負載均衡: 負載均衡.md
    - 其他:
        - Xamarin: 其他/Xamarin.md
        - Web節奏: 其他/Web節奏.md
        - Git: 其他/Git.md
        - SSH: 其他/Ssh轉發.md
        - DataBase: 其他/DataBase.md
    - MkDocs: MkDocs.md